version: '3.8'

services:
  finance-portal:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///finance_portal.db
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped 