apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-portal-config
  namespace: finance-portal
data:
  FLASK_APP: "run.py"
  FLASK_ENV: "production"
  SECRET_KEY: "your-secret-key-change-in-production"
  DATABASE_URL: "sqlite:///finance_portal.db"
  APP_NAME: "Personal Finance Portal"
  ITEMS_PER_PAGE: "10"
  MAX_CONTENT_LENGTH: "16777216" 