apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finance-portal

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: personal-finance-portal
  version: v1.0.0 