apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finance-portal-pvc
  namespace: finance-portal
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 