apiVersion: v1
kind: PersistentVolume
metadata:
  name: finance-portal-pv
  namespace: finance-portal
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/finance-portal-data"
  persistentVolumeReclaimPolicy: Retain 